import "./global.css";
import { Roboto } from "next/font/google";
import Navbar from "./components/Navbar/Navbar";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <Navbar />
        
        {children}
      </body>
    </html>
  );
}
